package com.innter.msdesigngarmentmaterial.repositories;

import com.innter.msdesigngarmentmaterial.entities.DesingMaterialClothGarmentGroupEntity;
import com.innter.msdesigngarmentmaterial.entities.DesingMaterialClothGarmentGroupKey;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

@Repository
public interface DesingMaterialClothGarmentGroupRepository extends JpaRepository<DesingMaterialClothGarmentGroupEntity, DesingMaterialClothGarmentGroupKey> {
}
